name: Depot Pull
description: Pull images from the Depot ephemeral registry.
author: Depot
branding:
  icon: package
  color: gray-dark
runs:
  using: node20
  main: dist/index.js
inputs:
  build-id:
    description: The build ID to pull.
    required: true
  platform:
    description: The platform to pull (defaults to the current platform).
    required: false
  tags:
    description: A list of tags to apply to the pulled image
    required: false
  token:
    description: If set, will populate the `DEPOT_TOKEN` environment variable.
    default: ''
    required: false
  target:
    description: Specific bake target to pull.
    default: ''
    required: false
